version: '3'
services:
  ace-judge-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - ace-judge-database
  ace-judge-database:
    image: mysql