version: '3'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - ./src:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://ace@mysql/ace
  mysql:
    image: wangxian/alpine-mysql
    environment:
      MYSQL_DATABASE: ace
      MYSQL_USER: ace
      MYSQL_PASSWORD: ace